---
title: "openHDF5"
author: "Max Joseph"
date: "June 20, 2016"
output: html_document
---

```{r load-libs}
library(raster)
library(rhdf5)
library(rgdal)
```

```{r define-file}
filename <- "../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"
```

```{r view-file}
h5ls(filename)
```

```{r spatial-info}
spatial_info <- h5read(filename, name = 'map info', read.attributes = TRUE)
```

```{r get-refl-metadata}
reflectance_info <- h5readAttributes(filename, name = 'Reflectance')
scale_factor <- reflectance_info$`Scale Factor`
fill_val <- reflectance_info$`data ignore value`
fill_val <- as.numeric(fill_val)
```

### Getting data dimensions

```{r get-dims}
file_id <- H5Fopen(filename)
data_id <- H5Dopen(file_id, 'Reflectance')
space <- H5Dget_space(data_id)
dims <- H5Sget_simple_extent_dims(space)$size
```

### Close connections

```{r close-connections}
H5Fclose(file_id)
H5Dclose(data_id)
H5Sclose(space)
```

## Read in and clean reflectance data

```{r}
b56 <- h5read(filename, 
              'Reflectance', 
              index = list(1:dims[1], 1:dims[2], 56))
b56 <- b56[, , 1]
image(b56)
```

```{r clean-data}
b56[b56 == fill_val] <- NA
b56 <- b56 / scale_factor
b56 <- t(b56)
```

## Embedding spatial information

```{r find-extent}
spatial_info <- strsplit(spatial_info, split = ',')
spatial_info <- unlist(spatial_info)
xmin <- as.numeric(spatial_info[4])
ymin <- as.numeric(spatial_info[5])

resolution <- as.numeric(spatial_info[6:7])
xmax <- xmin + dims[1] * resolution[1]
ymax <- ymin + dims[2] * resolution[2]
```

```{r set-extent}
ex <- extent(c(xmin, xmax, ymin, ymax))
```

```{r make-raster}
r56 <- raster(b56, crs = '+init=epsg:32611')
extent(r56) <- ex
plot(r56)
```


## Use NEON functions

```{r neon-functions}
# devtools::install_github('lwasser/neon-aop-package/neonAOP')
library(neonAOP)
r <- open_band(filename, 56, epsg = 32611)
plot(r)

bands <- c(58, 34, 19)
rgbstack <- create_stack(filename, bands, epsg = 32611)
plotRGB(rgbstack, stretch = 'lin')
```
